version: "3"

services:
  broker:
    image: dendebaiano/suricato-mqtt:v1.6.9
    networks:
      - rede-suricato
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
volumes:
  node-red-data:

networks:
  rede-suricato:
    driver: overlay

